#!/bin/sh
#
# @name x500 Quadrotor SITL
#
# @type Quadrotor Wide
#
#
#

. ${R}etc/init.d/rc.mc_defaults

# Position gains
param set-default MPC_XY_P 0.95
param set-default MPC_Z_P 1.0
# Velocity gains
param set-default MPC_XY_VEL_P_ACC 1.8
param set-default MPC_XY_VEL_I_ACC 0.4
param set-default MPC_XY_VEL_D_ACC 0.2

param set-default MPC_Z_VEL_P_ACC 4.0
param set-default MPC_Z_VEL_I_ACC 2.0
param set-default MPC_Z_VEL_D_ACC 0.0

# Roll gain
param set-default MC_ROLL_P 6.5

# Pitch gain
param set-default MC_PITCH_P 6.5

# Yaw gain
param set-default MC_YAW_P 2.8

# Rollrate gains
param set-default MC_ROLLRATE_P 0.15
param set-default MC_ROLLRATE_I 0.2
param set-default MC_ROLLRATE_D 0.003
param set-default MC_ROLLRATE_K 1

# Pitchrate gains
param set-default MC_PITCHRATE_P 0.15
param set-default MC_PITCHRATE_I 0.2
param set-default MC_PITCHRATE_D 0.003
param set-default MC_PITCHRATE_K 1

# Yawrate gains
param set-default MC_YAWRATE_P 0.2
param set-default MC_YAWRATE_I 0.1
param set-default MC_YAWRATE_D 0.0
param set-default MC_YAWRATE_K 1

set MIXER quad_x
